CREATE DATABASE P1700
GO

USE P1700
GO

---------------------------------------------------------

DROP TABLE IF EXISTS ERRORES_PROCEDIMIENTO
GO

CREATE TABLE ERRORES_PROCEDIMIENTO (
    ID_ERROR_PROCEDIMIENTO BIGINT IDENTITY(1,1) NOT NULL,
    BLOQUE SMALLINT NULL DEFAULT -1,
    NUMERO_ERROR INT NULL DEFAULT -1,
    IMPORTANCIA INT NULL DEFAULT -1,
    ESTADO INT NULL DEFAULT -1,
    PROCEDIMIENTO NVARCHAR(200) NULL DEFAULT '',
    LINEA INT NULL DEFAULT -1,
    MENSAJE_BD NVARCHAR(2000) NULL DEFAULT '',
    MENSAJE NVARCHAR(200) NULL DEFAULT '',

    FECHA_INCLUSION DATE DEFAULT GETDATE() NOT NULL,
    CEDULA_INCLUSION VARCHAR(20) NOT NULL DEFAULT '-1',

    CONSTRAINT PK_ERRORES_PROCEDIMIENTO PRIMARY KEY(ID_ERROR_PROCEDIMIENTO)
);

---------------------------------------------------------

-- Eliminar tabla si existe
DROP TABLE IF EXISTS PERFILES
GO

-- Crear tabla PERFILES
CREATE TABLE PERFILES (
    ID_PERFIL INT IDENTITY(1, 1),
    PERFIL VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(100) DEFAULT '',
    ESTADO BIT DEFAULT 1,

    FECHA_INCLUSION DATE DEFAULT GETDATE() NOT NULL,
    CEDULA_INCLUSION VARCHAR(20) NOT NULL DEFAULT ''

    CONSTRAINT PK_PERFILES PRIMARY KEY(ID_PERFIL)
);

-- Índice en la columna PERFIL
CREATE INDEX IX_PERFIL
ON PERFILES (PERFIL);

---------------------------------------------------------

-- Eliminar tabla si existe
DROP TABLE IF EXISTS USUARIOS
GO

-- Crear tabla USUARIOS
CREATE TABLE USUARIOS (
    ID_USUARIO INT IDENTITY(1, 1),
    CEDULA VARCHAR(20) NOT NULL,
    CONTRASENIA VARCHAR(100) NOT NULL,
    ID_PERFIL INT NOT NULL,
    ESTADO BIT DEFAULT 1,

    FECHA_INCLUSION SMALLDATETIME DEFAULT GETDATE() NOT NULL,
    CEDULA_INCLUSION VARCHAR(20) NOT NULL DEFAULT ''

    CONSTRAINT PK_USUARIOS PRIMARY KEY(ID_USUARIO)
);
GO

-- Índice en la columna NOMBRE
CREATE INDEX IX_CEDULA
ON USUARIOS (CEDULA);
GO

-- LLAVE FORANEA USUARIOS_VS_PERFILES
ALTER TABLE USUARIOS
ADD CONSTRAINT USUARIOS_VS_PERFILES
FOREIGN KEY (ID_PERFIL) REFERENCES PERFILES(ID_PERFIL);

---------------------------------------------------------

-- Eliminar tabla si existe
DROP TABLE IF EXISTS PERMISOS
GO

-- Crear tabla PERMISOS
CREATE TABLE PERMISOS (
    ID_PERMISO INT IDENTITY(1, 1),
    PERMISO VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(100) DEFAULT '',
    ESTADO BIT DEFAULT 1,

    FECHA_INCLUSION DATE DEFAULT GETDATE() NOT NULL,
    CEDULA_INCLUSION VARCHAR(20) NOT NULL DEFAULT ''

    CONSTRAINT PK_PERMISOS PRIMARY KEY(ID_PERMISO)
);

-- Índice en la columna PERMISO
CREATE INDEX IX_PERMISO
ON PERMISOS (PERMISO);

---------------------------------------------------------

-- Eliminar tabla si existe
DROP TABLE IF EXISTS PERFILES_PERMISOS
GO

-- Crear tabla PERMISOS_PERFILES
CREATE TABLE PERMISOS_PERFILES (
    ID_PERMISO_PERFIL INT IDENTITY(1, 1),
    ID_PERFIL INT NOT NULL,
    ID_PERMISO INT NOT NULL,
    
    FECHA_INCLUSION DATE DEFAULT GETDATE() NOT NULL

    CONSTRAINT PK_PERMISOS_PERFILES PRIMARY KEY(ID_PERMISO_PERFIL)
);

-- LLAVE FORANEA PERMISOS_PERFILES_VS_PERFILES
ALTER TABLE PERMISOS_PERFILES
ADD CONSTRAINT PERMISOS_PERFILES_VS_PERFILES
FOREIGN KEY (ID_PERFIL) REFERENCES PERFILES(ID_PERFIL);

-- LLAVE FORANEA PERMISOS_PERFILES_VS_PERMISOS
ALTER TABLE PERMISOS_PERFILES
ADD CONSTRAINT PERMISOS_PERFILES_VS_PERMISOS
FOREIGN KEY (ID_PERMISO) REFERENCES PERMISOS(ID_PERMISO);

---------------------------------------------------------

-- Eliminar tabla si existe
DROP TABLE IF EXISTS TIENDAS
GO

-- Crear tabla TIENDAS
CREATE TABLE TIENDAS (
    ID_TIENDA INT IDENTITY(1, 1),
    TIENDA VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(100) DEFAULT '',
    ESTADO BIT DEFAULT 1,

    FECHA_INCLUSION DATE DEFAULT GETDATE() NOT NULL,
    CEDULA_INCLUSION VARCHAR(20) NOT NULL DEFAULT ''

    CONSTRAINT PK_TIENDAS PRIMARY KEY(ID_TIENDA)
);

-- Índice en la columna TIENDA
CREATE INDEX IX_TIENDA
ON TIENDAS (TIENDA);

---------------------------------------------------------

-- Eliminar tabla si existe
DROP TABLE IF EXISTS EMPLEADOS
GO

-- Crear tabla EMPLEADOS
CREATE TABLE EMPLEADOS (
    ID_EMPLEADO INT IDENTITY(1, 1),
    NOMBRE VARCHAR(100) NOT NULL DEFAULT '',
    TELEFONO VARCHAR(20) DEFAULT '',
    SALARIO DECIMAL(11,2) DEFAULT 0,
    ID_USUARIO INT NOT NULL,
    ID_TIENDA INT NOT NULL,
    ESTADO BIT DEFAULT 1,
    ES_SUPERVISOR BIT DEFAULT 0,
    FECHA_INCLUSION DATE DEFAULT GETDATE() NOT NULL,
    CEDULA_INCLUSION VARCHAR(20) NOT NULL DEFAULT ''

    CONSTRAINT PK_EMPLEADOS PRIMARY KEY(ID_EMPLEADO)
);

-- Índice en la columna NOMBRE
CREATE INDEX IX_NOMBRE
ON EMPLEADOS (NOMBRE);

-- LLAVE FORANEA EMPLEADOS_VS_USUARIOS
ALTER TABLE EMPLEADOS
ADD CONSTRAINT EMPLEADOS_VS_USUARIOS
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO);

-- LLAVE FORANEA EMPLEADOS_VS_TIENDAS
ALTER TABLE EMPLEADOS
ADD CONSTRAINT EMPLEADOS_VS_TIENDAS
FOREIGN KEY (ID_TIENDA) REFERENCES TIENDAS(ID_TIENDA);

---------------------------------------------------------

-- Modificar tabla Empleados
ALTER TABLE EMPLEADOS
ADD ID_SUPERVISOR INT;

-- LLAVE FORANEA EMPLEADOS_VS_EMPLEADOS
ALTER TABLE EMPLEADOS
ADD CONSTRAINT FK_EMPLEADOS_VS_EMPLEADOS
FOREIGN KEY (ID_SUPERVISOR) REFERENCES EMPLEADOS(ID_EMPLEADO);

---------------------------------------------------------


DROP TABLE IF EXISTS ERRORES_PROCEDIMIENTO
GO

CREATE TABLE ERRORES_PROCEDIMIENTO (
    ID_ERROR_PROCEDIMIENTO BIGINT IDENTITY(1,1) NOT NULL,
    BLOQUE SMALLINT NULL DEFAULT -1,
    NUMERO_ERROR INT NULL DEFAULT -1,
    IMPORTANCIA INT NULL DEFAULT -1,
    ESTADO INT NULL DEFAULT -1,
    PROCEDIMIENTO NVARCHAR(200) NULL DEFAULT '',
    LINEA INT NULL DEFAULT -1,
    MENSAJE_BD NVARCHAR(2000) NULL DEFAULT '',
    MENSAJE NVARCHAR(200) NULL DEFAULT '',

    FECHA_INCLUSION DATE DEFAULT GETDATE() NOT NULL,
    CEDULA_INCLUSION VARCHAR(20) NOT NULL DEFAULT '-1',

    CONSTRAINT PK_ERRORES_PROCEDIMIENTO PRIMARY KEY(ID_ERROR_PROCEDIMIENTO)
);

---------------------------------------------------------
