USE P1700
GO

---------------------------------------------------------

DROP VIEW IF EXISTS EMPLEADOS_VISTA
GO

--VISTA PARA EMPLEADOS
CREATE VIEW EMPLEADOS_VISTA
AS

  SELECT
    EMPLEADO.[ID_EMPLEADO],
    EMPLEADO.[NOMBRE],
		EMPLEADO.[TELEFONO],
		EMPLEADO.[FECHA_INCLUSION],
		CASE WHEN EMPLEADO.ES_SUPERVISOR = 0 THEN 'OPERARIO' ELSE 'SUPERVISOR' END AS TIPO,
		EMPLEADO.[SALARIO],
		SUPERVISOR.[ID_EMPLEADO] AS ID_SUPERVISOR,
		SUPERVISOR.[NOMBRE] AS SUPERVISOR
  FROM 
    [EMPLEADOS] EMPLEADO
	LEFT JOIN [EMPLEADOS] SUPERVISOR ON EMPLEADO.[ID_SUPERVISOR] = SUPERVISOR.[ID_EMPLEADO];

GO

---------------------------------------------------------

