USE P1700
GO

INSERT INTO PERFILES (PERFIL) VALUES ('Administrador');
INSERT INTO PERFILES (PERFIL) VALUES ('Encargado');
INSERT INTO PERFILES (PERFIL) VALUES ('Auditoria');
GO

INSERT INTO PERMISOS (PERMISO) VALUES ('Registro de Empleados');
INSERT INTO PERMISOS (PERMISO) VALUES ('Consulta de Empleados');
INSERT INTO PERMISOS (PERMISO) VALUES ('Consulta de Perfiles');
GO

INSERT INTO TIENDAS (TIENDA) VALUES ('Zapote');
INSERT INTO TIENDAS (TIENDA) VALUES ('San Pedro');
INSERT INTO TIENDAS (TIENDA) VALUES ('Heredia');
INSERT INTO TIENDAS (TIENDA) VALUES ('San José');
GO

INSERT INTO PERMISOS_PERFILES (ID_PERFIL, ID_PERMISO) VALUES (1, 1);
INSERT INTO PERMISOS_PERFILES (ID_PERFIL, ID_PERMISO) VALUES (1, 2);
INSERT INTO PERMISOS_PERFILES (ID_PERFIL, ID_PERMISO) VALUES (1, 3);
INSERT INTO PERMISOS_PERFILES (ID_PERFIL, ID_PERMISO) VALUES (2, 1);
INSERT INTO PERMISOS_PERFILES (ID_PERFIL, ID_PERMISO) VALUES (3, 2);
INSERT INTO PERMISOS_PERFILES (ID_PERFIL, ID_PERMISO) VALUES (3, 3);
GO

INSERT INTO USUARIOS ([CEDULA], [CONTRASENIA], [ID_PERFIL]) VALUES ('DEFAULT', '', 1);
INSERT INTO EMPLEADOS ([NOMBRE], [TELEFONO], [SALARIO], [ID_USUARIO], [ID_TIENDA], [ID_SUPERVISOR], [ES_SUPERVISOR]) VALUES ('Heiner Andres Solano Rosas', '86864389', 1.00, 1, 1, 1, 1);
INSERT INTO EMPLEADOS ([NOMBRE], [TELEFONO], [SALARIO], [ID_USUARIO], [ID_TIENDA], [ID_SUPERVISOR], [ES_SUPERVISOR]) VALUES ('Juliana Bosch', '81864381', 500000.00, 1, 2, 1, 1);
INSERT INTO EMPLEADOS ([NOMBRE], [TELEFONO], [SALARIO], [ID_USUARIO], [ID_TIENDA], [ID_SUPERVISOR]) VALUES ('Concepcion Ariza', '68864365', 800000.00, 1, 3, 1);
INSERT INTO EMPLEADOS ([NOMBRE], [TELEFONO], [SALARIO], [ID_USUARIO], [ID_TIENDA], [ID_SUPERVISOR]) VALUES ('Barbara Gisbert', '88864360', 850000.00, 1, 2, 1);
INSERT INTO EMPLEADOS ([NOMBRE], [TELEFONO], [SALARIO], [ID_USUARIO], [ID_TIENDA], [ID_SUPERVISOR]) VALUES ('Maria Gracia Ribas', '68864360', 400000.00, 1, 2, 1);
INSERT INTO EMPLEADOS ([NOMBRE], [TELEFONO], [SALARIO], [ID_USUARIO], [ID_TIENDA], [ID_SUPERVISOR]) VALUES ('Esteban Rivas', '61814160', 450000.00, 1, 1, 1);
INSERT INTO EMPLEADOS ([NOMBRE], [TELEFONO], [SALARIO], [ID_USUARIO], [ID_TIENDA], [ID_SUPERVISOR]) VALUES ('Maria Natividad Puertas', '78864360', 650000.00, 1, 1, 1);
INSERT INTO EMPLEADOS ([NOMBRE], [TELEFONO], [SALARIO], [ID_USUARIO], [ID_TIENDA], [ID_SUPERVISOR]) VALUES ('Alonso Amador Blazquez', '74864369', 800000.00, 1, 1, 1);
INSERT INTO EMPLEADOS ([NOMBRE], [TELEFONO], [SALARIO], [ID_USUARIO], [ID_TIENDA], [ID_SUPERVISOR]) VALUES ('Juan Fernando Morillo', '78864361', 700000.00, 1, 3, 1);
INSERT INTO EMPLEADOS ([NOMBRE], [TELEFONO], [SALARIO], [ID_USUARIO], [ID_TIENDA], [ID_SUPERVISOR]) VALUES ('Rachida Solano', '88854760', 400000.00, 1, 3, 1);
INSERT INTO EMPLEADOS ([NOMBRE], [TELEFONO], [SALARIO], [ID_USUARIO], [ID_TIENDA], [ID_SUPERVISOR]) VALUES ('Eloy Sainz', '88869360', 500000.00, 1, 1, 2);
INSERT INTO EMPLEADOS ([NOMBRE], [TELEFONO], [SALARIO], [ID_USUARIO], [ID_TIENDA], [ID_SUPERVISOR]) VALUES ('Maria Blanca Rodrguez', '88864360', 500000.00, 1, 3, 2);
INSERT INTO EMPLEADOS ([NOMBRE], [TELEFONO], [SALARIO], [ID_USUARIO], [ID_TIENDA], [ID_SUPERVISOR]) VALUES ('Yaiza Perello', '87864360', 550000.00, 1, 2, 2);
INSERT INTO EMPLEADOS ([NOMBRE], [TELEFONO], [SALARIO], [ID_USUARIO], [ID_TIENDA], [ID_SUPERVISOR]) VALUES ('Noe Lago', '68861360', 700000.00, 1, 4, 2);
GO
